Repository prgrms-be-devcourse/NBE3-4-3-Team09, pull requests merged in 2025-03, with the labels that each got.

#8 [FEAT] : U-00 #3
  .github/workflows/build-test.yml
  backend/src/main/java/com/backend/domain/user/dto/request/UserModifyProfileRequest.java
  backend/src/main/java/com/backend/domain/user/service/UserService.java
  backend/src/main/java/com/backend/domain/user/service/UserService.kt
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetails.java
  backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java
Labels: migration

#12 [REFACTOR] V-01
  backend/src/main/java/com/backend/domain/voter/service/VoterService.java
  backend/src/test/java/com/backend/domain/voter/ApiV1VoterControllerTest.java
Labels: migration

#17 CG-01 #6
  backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java
  backend/src/main/java/com/backend/domain/category/dto/request/CategoryRequest.java
  backend/src/main/java/com/backend/domain/category/dto/request/CategoryRequest.kt
  backend/src/main/java/com/backend/domain/category/dto/response/CategoryResponse.java
  backend/src/main/java/com/backend/domain/category/dto/response/CategoryResponse.kt
  backend/src/main/java/com/backend/domain/category/entity/Category.java
  backend/src/main/java/com/backend/domain/category/entity/Category.kt
  backend/src/main/java/com/backend/global/baseentity/BaseInitData.java
Labels: migration

#19 [REFACTOR] CH-01
  backend/src/main/java/com/backend/domain/chat/controller/ApiV1ChatController.java
  backend/src/main/java/com/backend/domain/chat/controller/ApiV1ChatController.kt
  backend/src/main/java/com/backend/domain/chat/controller/ApiV1ChatMessageController.java
  backend/src/main/java/com/backend/domain/chat/controller/ApiV1ChatMessageController.kt
  backend/src/main/java/com/backend/domain/chat/controller/WebSocketEventController.java
  backend/src/main/java/com/backend/domain/chat/controller/WebSocketEventController.kt
  backend/src/main/java/com/backend/domain/chat/converter/ChatConverter.java
  backend/src/main/java/com/backend/domain/chat/converter/ChatConverter.kt
  backend/src/main/java/com/backend/domain/chat/dto/request/ChatRequest.java
  backend/src/main/java/com/backend/domain/chat/dto/request/ChatRequest.kt
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatResponse.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatResponse.kt
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatResponses.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatResponses.kt
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatsInPost.java
  backend/src/main/java/com/backend/domain/chat/entity/Chat.java
  backend/src/main/java/com/backend/domain/chat/entity/Chat.kt
  backend/src/main/java/com/backend/domain/chat/entity/MessageType.java
  backend/src/main/java/com/backend/domain/chat/entity/MessageType.kt
  backend/src/main/java/com/backend/domain/chat/exception/WebSocketException.java
  backend/src/main/java/com/backend/domain/chat/exception/WebSocketException.kt
  backend/src/main/java/com/backend/domain/chat/handler/StompHandler.java
  backend/src/main/java/com/backend/domain/chat/handler/WebSocketEventListener.java
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepository.kt
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepositoryImpl.java
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepositoryImpl.kt
  backend/src/main/java/com/backend/domain/chat/repository/CustomChatRepository.java
  backend/src/main/java/com/backend/domain/chat/repository/CustomChatRepository.kt
  backend/src/main/java/com/backend/domain/chat/service/ChatService.java
  backend/src/main/java/com/backend/domain/chat/service/ChatService.kt
  backend/src/main/java/com/backend/global/baseentity/BaseInitData.java
  backend/src/main/java/com/backend/global/config/RedisConfig.java
  backend/src/main/java/com/backend/global/config/RedisConfig.kt
  backend/src/main/java/com/backend/global/config/WebSocketConfig.java
  backend/src/main/java/com/backend/global/config/WebSocketConfig.kt
  backend/src/main/java/com/backend/global/redis/service/RedisPublisher.java
  backend/src/main/java/com/backend/global/redis/service/RedisPublisher.kt
  backend/src/main/java/com/backend/global/redis/service/RedisSubscriber.java
  backend/src/main/java/com/backend/global/redis/service/RedisSubscriber.kt
  backend/src/main/resources/mail-templates/index.html
  backend/src/test/java/com/backend/domain/chat/ChatControllerTest.java
  backend/src/test/java/com/backend/domain/chat/util/ChatObjectProvider.java
Labels: migration

#22 [REFACTOR] J-01
  backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.java
  backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.kt
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingDetailResponse.java
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingDetailResponse.kt
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingPageResponse.java
  backend/src/main/java/com/backend/domain/jobposting/dto/JobPostingPageResponse.kt
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingQueryRepository.java
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingQueryRepository.kt
  backend/src/main/java/com/backend/domain/jobposting/service/JobPostingService.java
  backend/src/main/java/com/backend/domain/jobposting/service/JobPostingService.kt
  backend/src/main/java/com/backend/domain/jobposting/util/JobPostingSearchCondition.java
  backend/src/main/java/com/backend/domain/jobposting/util/JobPostingSearchCondition.kt
  backend/src/main/java/com/backend/domain/jobskill/dto/JobSkillResponse.kt
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillJpaRepository.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillJpaRepository.kt
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepository.kt
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepositoryImpl.java
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepositoryImpl.kt
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostJpaRepository.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentAuthorController.java
  backend/src/main/java/com/backend/domain/user/dto/response/UserGetProfileResponse.java
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
Labels: migration

#24 CO-01
  backend/.gitignore
  backend/src/main/java/com/backend/domain/comment/dto/request/CommentRequestDto.java
  backend/src/main/java/com/backend/domain/comment/entity/Comment.java
  backend/src/main/java/com/backend/domain/comment/entity/Comment.kt
  backend/src/main/java/com/backend/domain/comment/service/CommentService.java
Labels: migration

#26 [REFACTOR] G-07
  .github/workflows/build-test.yml
  backend/src/main/java/com/backend/global/response/GenericResponse.java
  backend/src/main/java/com/backend/global/response/GenericResponse.kt
Labels: migration

#27 [REFACTOR] : U-03 #20
  backend/src/main/java/com/backend/domain/user/controller/ApiV1UserController.kt
  backend/src/main/java/com/backend/domain/user/entity/SiteUser.kt
  backend/src/main/java/com/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/backend/domain/user/repository/UserRepository.kt
  backend/src/main/java/com/backend/domain/user/service/UserService.kt
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetailsService.java
  backend/src/main/java/com/backend/global/security/oauth/CustomOAuth2UserService.java
  backend/src/test/java/com/backend/domain/category/CategoryControllerTest.java
  backend/src/test/java/com/backend/domain/comment/ApiV1CommentControllerTest.java
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentAuthorTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentUserTest.java
  backend/src/test/java/com/backend/domain/voter/ApiV1VoterControllerTest.java
  backend/src/test/java/com/backend/global/security/oauth/CustomOAuth2UserServiceTest.java
Labels: migration

#33 [REFACTOR] : G-00 #28
  backend/src/main/java/com/backend/global/response/GenericResponse.kt
  backend/src/main/java/com/backend/global/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/security/SecurityConfig.kt
  backend/src/main/java/com/backend/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/backend/global/security/handler/JwtLogoutHandler.java
  backend/src/main/java/com/backend/global/security/handler/JwtLogoutSuccessHandler.java
Labels: migration

#35 [REFACTOR] : G-01 #34
  backend/src/main/java/com/backend/domain/jobposting/controller/ApiV1JobPostingController.kt
  backend/src/main/java/com/backend/domain/user/dto/request/JobSkillRequest.kt
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetails.java
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetails.kt
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetailsService.java
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetailsService.kt
Labels: migration

#29 [REFACTOR] P-01 #5
  backend/.gitignore
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.java
  backend/src/main/java/com/backend/domain/post/dto/FreePostRequest.java
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostRequest.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/entity/Post.kt
  backend/src/main/java/com/backend/domain/post/entity/RecruitmentPost.java
  backend/src/main/java/com/backend/domain/post/entity/RecruitmentPost.kt
  backend/src/main/java/com/backend/domain/post/repository/post/PostQueryRepository.java
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostJpaRepository.java
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostQueryRepository.java
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java
  backend/src/main/java/com/backend/domain/user/entity/SiteUser.kt
  backend/src/main/java/com/backend/domain/voter/service/VoterService.java
  backend/src/main/java/com/backend/global/baseentity/BaseEntity.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentMailTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentUserTest.java
Labels: migration

#32 [REFACTOR] J-02
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingJpaRepository.kt
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingQueryRepository.kt
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepository.kt
  backend/src/main/java/com/backend/domain/jobposting/repository/JobPostingRepositoryImpl.kt
  backend/src/main/java/com/backend/domain/jobposting/service/JobPostingService.kt
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillJpaRepository.kt
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepository.kt
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillRepositoryImpl.kt
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/test/java/com/backend/domain/jobposting/ApiV1JobPostingControllerTest.java
Labels: migration

#37 [REFACTOR] V-01
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.java
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/entity/RecruitmentPost.kt
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/voter/controller/ApiV1VoterController.java
  backend/src/main/java/com/backend/domain/voter/controller/ApiV1VoterController.kt
  backend/src/main/java/com/backend/domain/voter/domain/VoterType.java
  backend/src/main/java/com/backend/domain/voter/domain/VoterType.kt
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateRequest.java
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateRequest.kt
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateResponse.java
  backend/src/main/java/com/backend/domain/voter/dto/VoterCreateResponse.kt
  backend/src/main/java/com/backend/domain/voter/repository/VoterJpaRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterJpaRepository.kt
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepository.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepository.kt
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepositoryImpl.java
  backend/src/main/java/com/backend/domain/voter/repository/VoterRepositoryImpl.kt
  backend/src/main/java/com/backend/domain/voter/service/VoterService.java
  backend/src/main/java/com/backend/domain/voter/service/VoterService.kt
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.java
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.kt
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.kt
  backend/src/main/java/com/backend/global/exception/GlobalException.java
  backend/src/main/java/com/backend/global/exception/GlobalException.kt
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetails.kt
  backend/src/main/java/com/backend/global/security/custom/CustomUserDetailsService.kt
  backend/src/test/java/com/backend/domain/voter/ApiV1VoterControllerTest.java
Labels: refactoring, migration

#38 [REFACTOR] : G-02 #36
  backend/src/main/java/com/backend/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthenticationFilter.kt
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.kt
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter2.java
  backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java
Labels: migration

#40 [REFACTOR] R-01 #30
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentAuthorController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/request/AuthorRequest.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/request/AuthorRequest.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserDetail.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserDetail.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserPageResponse.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserPageResponse.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserPostResponse.java
  backend/src/main/java/com/backend/domain/recruitmentUser/dto/response/RecruitmentUserPostResponse.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUser.java
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUser.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUserStatus.java
  backend/src/main/java/com/backend/domain/recruitmentUser/entity/RecruitmentUserStatus.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentMailTest.java
Labels: migration

#42 [REFACTOR] G-06
  backend/src/main/java/com/backend/domain/category/entity/Category.kt
  backend/src/main/java/com/backend/global/baseentity/BaseEntity.kt
Labels: refactoring, migration

#44 [REFACTOR] G-07
  backend/src/main/java/com/backend/domain/jobskill/entity/JobSkill.kt
  backend/src/main/java/com/backend/global/redis/repository/RedisRepository.java
  backend/src/main/java/com/backend/global/redis/repository/RedisRepository.kt
  backend/src/main/java/com/backend/global/scheduler/service/SchedulerService.java
  backend/src/main/java/com/backend/global/security/filter/JwtAuthenticationFilter.kt
  backend/src/main/java/com/backend/global/security/filter/JwtAuthorizationFilter.kt
Labels: refactoring, migration

#45 [REFACTOR] : G-03 #41
  backend/src/main/java/com/backend/domain/jobskill/repository/JobSkillJpaRepository.kt
  backend/src/main/java/com/backend/domain/user/entity/SiteUser.kt
  backend/src/main/java/com/backend/domain/user/service/UserService.kt
  backend/src/test/java/com/backend/domain/user/ApiV1UserControllerTest.java
Labels: migration

#50 CG-02 #21
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.java
  backend/src/main/java/com/backend/domain/category/controller/CategoryController.kt
  backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.java
  backend/src/main/java/com/backend/domain/category/converter/CategoryConverter.kt
  backend/src/main/java/com/backend/domain/category/domain/CategoryName.java
  backend/src/main/java/com/backend/domain/category/domain/CategoryName.kt
  backend/src/main/java/com/backend/domain/category/dto/response/CategoryResponse.kt
  backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.java
  backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.kt
  backend/src/main/java/com/backend/domain/category/service/CategoryService.java
  backend/src/main/java/com/backend/domain/category/service/CategoryService.kt
Labels: migration

#51 [REFACTOR] G-09
  backend/src/main/java/com/backend/global/aspect/ResponseAspect.kt
Labels: migration

#53 [REFACTOR] G-10
  backend/src/main/java/com/backend/global/config/AppConfig.kt
  backend/src/main/java/com/backend/global/config/AsyncConfig.java
  backend/src/main/java/com/backend/global/config/AsyncConfig.kt
  backend/src/main/java/com/backend/global/config/JpaAuditingConfig.kt
  backend/src/main/java/com/backend/global/config/MailConfig.java
  backend/src/main/java/com/backend/global/config/MailConfig.kt
  backend/src/main/java/com/backend/global/config/MongoDBConfig.java
  backend/src/main/java/com/backend/global/config/MongoDBConfig.kt
  backend/src/main/java/com/backend/global/config/QuerydslConfig.kt
Labels: migration

#54 [Refactor] R-03
  backend/src/main/java/com/backend/domain/chat/handler/StompHandler.java
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentAuthorController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentAuthorController.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/repository/RecruitmentUserRepository.java
  backend/src/main/java/com/backend/domain/recruitmentUser/repository/RecruitmentUserRepository.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.java
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentMailTest.java
Labels: migration

#56 R-02 #46
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.java
  backend/src/main/java/com/backend/domain/recruitmentUser/controller/ApiV1RecruitmentUserController.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.kt
Labels: migration

#57 [REFACTOR] M-01
  backend/build.gradle.kts
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.kt
  backend/src/main/java/com/backend/global/mail/service/MailService.java
  backend/src/main/java/com/backend/global/mail/service/MailService.kt
  backend/src/main/java/com/backend/global/mail/service/MailServiceImpl.java
  backend/src/main/java/com/backend/global/mail/service/MailServiceImpl.kt
  backend/src/main/java/com/backend/global/mail/util/EmailTemplateMaker.java
  backend/src/main/java/com/backend/global/mail/util/EmailTemplateMaker.kt
  backend/src/main/java/com/backend/global/mail/util/MailSender.kt
  backend/src/main/java/com/backend/global/mail/util/MailSenderImpl.java
  backend/src/main/java/com/backend/global/mail/util/MailSenderImpl.kt
  backend/src/main/java/com/backend/global/mail/util/TemplateMaker.kt
  backend/src/main/java/com/backend/global/mail/util/TemplateName.kt
  backend/src/test/resources/application-test.yml
Labels: migration

#58 [REFACTOR] : G-08 #47
  backend/build.gradle.kts
  backend/src/main/java/com/backend/global/scheduler/apiresponse/Job.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/Jobs.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/JobsDetail.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/company/CompanyDetailDto.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/company/CompanyDto.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/position/ExperienceLevelDto.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/position/JobCodeDto.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/position/PositionDto.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/position/RequireEducateDto.java
  backend/src/main/java/com/backend/global/scheduler/apiresponse/salary/SalaryDto.java
  backend/src/main/java/com/backend/global/scheduler/service/SchedulerService.java
  backend/src/main/java/com/backend/global/scheduler/service/SchedulerService.kt
  backend/src/main/java/com/backend/global/scheduler/service/SchedulerService2.java
Labels: migration

#59 [Refactor] CH-02
  backend/src/test/java/com/backend/domain/chat/ChatControllerTest.java
  backend/src/test/resources/application-test.yml
Labels: refactoring

#61 [REFACTOR] P-02 #39
  backend/src/main/java/com/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1RecruitmentPostController.java
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.java
  backend/src/main/java/com/backend/domain/post/dto/FreePostRequest.java
  backend/src/main/java/com/backend/domain/post/dto/FreePostRequest.kt
  backend/src/main/java/com/backend/domain/post/dto/PostCreateResponse.java
  backend/src/main/java/com/backend/domain/post/dto/PostCreateResponse.kt
  backend/src/main/java/com/backend/domain/post/dto/PostPageResponse.java
  backend/src/main/java/com/backend/domain/post/dto/PostPageResponse.kt
  backend/src/main/java/com/backend/domain/post/dto/PostRequestDto.java
  backend/src/main/java/com/backend/domain/post/dto/PostRequestDto.kt
  backend/src/main/java/com/backend/domain/post/dto/PostResponse.java
  backend/src/main/java/com/backend/domain/post/dto/PostResponse.kt
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostRequest.java
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostRequest.kt
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostResponse.java
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostResponse.kt
  backend/src/main/java/com/backend/domain/post/entity/Post.java
  backend/src/main/java/com/backend/domain/post/entity/Post.kt
  backend/src/main/java/com/backend/domain/post/entity/RecruitmentPost.kt
  backend/src/main/java/com/backend/domain/post/repository/post/PostJpaRepository.java
  backend/src/main/java/com/backend/domain/post/repository/post/PostJpaRepository.kt
  backend/src/main/java/com/backend/domain/post/repository/post/PostQueryRepository.java
  backend/src/main/java/com/backend/domain/post/repository/post/PostQueryRepository.kt
  backend/src/main/java/com/backend/domain/post/repository/post/PostRepository.java
  backend/src/main/java/com/backend/domain/post/repository/post/PostRepository.kt
  backend/src/main/java/com/backend/domain/post/repository/post/PostRepository2.java
  backend/src/main/java/com/backend/domain/post/repository/post/PostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/post/repository/post/PostRepositoryImpl.kt
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostJpaRepository.java
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostJpaRepository.kt
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostQueryRepository.java
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostQueryRepository.kt
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostRepository.java
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostRepository.kt
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostRepositoryImpl.java
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostRepositoryImpl.kt
  backend/src/main/java/com/backend/domain/post/service/FreePostService.java
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/domain/post/service/PostService2.java
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/post/util/PostSearchCondition.java
  backend/src/main/java/com/backend/domain/post/util/PostSearchCondition.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.kt
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentUserService.kt
  backend/src/test/java/com/backend/domain/comment/ApiV1CommentControllerTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentMailTest.java
  backend/src/test/java/com/backend/domain/recruitment/RecruitmentUserTest.java
Labels: migration

#64 [REFACTOR] G-11
  backend/src/main/java/com/backend/global/advice/GlobalControllerAdvice.kt
  backend/src/main/java/com/backend/global/response/ErrorDetail.java
  backend/src/main/java/com/backend/global/response/ErrorDetail.kt
  backend/src/main/java/com/backend/global/validator/EnumValidator.java
  backend/src/main/java/com/backend/global/validator/ValidEnum.java
Labels: migration

#68 [FEATURE] R-04
  backend/src/main/java/com/backend/domain/recruitmentUser/service/RecruitmentAuthorService.kt
  backend/src/main/java/com/backend/global/mail/service/MailService.kt
  backend/src/main/java/com/backend/global/mail/service/MailServiceImpl.kt
  backend/src/main/java/com/backend/global/mail/util/TemplateName.kt
  backend/src/main/java/com/backend/global/scheduler/service/JobPostingSchedulerService.kt
  backend/src/main/java/com/backend/global/scheduler/service/RecruitmentSchedulerService.kt
  backend/src/main/resources/mail-templates/recruitment-end-template.html
Labels: enhancement

#69 [REFACTOR] P-03 #62
  backend/src/main/java/com/backend/domain/post/controller/ApiV1FreePostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1FreePostController.kt
  backend/src/main/java/com/backend/domain/post/controller/ApiV1FreePostController2.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1PostController.kt
  backend/src/main/java/com/backend/domain/post/controller/ApiV1RecruitmentPostController.java
  backend/src/main/java/com/backend/domain/post/controller/ApiV1RecruitmentPostController.kt
  backend/src/main/java/com/backend/domain/post/controller/ApiV1RecruitmentPostController2.java
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.java
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.kt
  backend/src/main/java/com/backend/domain/post/service/FreePostService.java
  backend/src/main/java/com/backend/domain/post/service/FreePostService.kt
  backend/src/main/java/com/backend/domain/post/service/PostService.java
  backend/src/main/java/com/backend/domain/post/service/PostService.kt
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.java
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.kt
Labels: migration

#70 [REFACTOR] R-04
  backend/src/main/java/com/backend/domain/category/repository/CategoryRepository.kt
  backend/src/main/java/com/backend/domain/post/conveter/PostConverter.kt
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostRequest.kt
  backend/src/main/java/com/backend/domain/post/dto/RecruitmentPostResponse.kt
  backend/src/main/java/com/backend/domain/post/entity/Post.kt
  backend/src/main/java/com/backend/domain/post/entity/RecruitmentPost.kt
  backend/src/main/java/com/backend/domain/post/repository/recruitment/RecruitmentPostQueryRepository.kt
  backend/src/main/java/com/backend/domain/post/service/FreePostService.kt
  backend/src/main/java/com/backend/domain/post/service/RecruitmentPostService.kt
Labels: refactoring
